### PR TITLE
bug(chat): set chat message max characters to 150

### LINKED ISSUE #290: Set a max of 150 characters per chat message

### PR DESCRIPTION
**Pull request by Mautjee**
## Description

This PR introduces a max amount of 150 Characters
 
## Related Issues

closes #290 

## Changes Made

- [FE] Update the input field in the chat view

### CODE REVIEW

File: src/constants/validation.ts [hunk 1]
```diff
@@ -49,6 +54,10 @@ export const validIssue = z
   .min(validation.textLength.long.min)
   .max(validation.textLength.long.max);
 
+export const validMessage = z
+  .string()
+  .max(validation.textLength.chatMessage.max);
+
 export const validUsername = z
```
Comment (silimarius) [inline src/constants/validation.ts:61]: Append "schema" at the end of these var names

File: src/components/chat/chat.tsx [hunk 2]
```diff
@@ -38,6 +44,27 @@ export const Chat: FC<Props> = ({ roomId, room }) => {
     setMessages((prev) => [...prev, newMessage]);
   };
 
+  const handleMessage = (event: { target: { value: string } }) => {
```
Comment (silimarius) [inline src/components/chat/chat.tsx:47]:
```suggestion
  const handleMessageChange = (event: { target: { value: string } }) => {
```

File: src/components/chat/chat.tsx [hunk 3]
```diff
@@ -38,6 +44,27 @@ export const Chat: FC<Props> = ({ roomId, room }) => {
...
+      setMessage(inputValue.slice(0, 150));
+    }
+  };
+
+  const [messageError, setValidation] = useState("");
+
+  const validateForm = (newMessage: string) => {
+    const error = !validMessage.safeParse(newMessage).success
+      ? textLength.chatMessage.error
+      : "";
```
Comment (silimarius) [inline src/components/chat/chat.tsx:64]:
```suggestion
    const error = validMessage.safeParse(newMessage).success
      ? ""
      : textLength.chatMessage.error;
```

File: src/components/chat/chat.tsx [hunk 4]
```diff
@@ -38,6 +44,27 @@ export const Chat: FC<Props> = ({ roomId, room }) => {
...
+    validateForm(inputValue);
+
+    if (!messageError && inputValue.length <= 150) {
+      setMessage(inputValue);
+    } else if (inputValue.length > 150) {
+      setMessage(inputValue.slice(0, 150));
+    }
+  };
+
+  const [messageError, setValidation] = useState("");
```
Comment (silimarius) [inline src/components/chat/chat.tsx:59]: Move above in the component

File: src/components/chat/chat.tsx [hunk 5]
```diff
@@ -38,6 +44,27 @@ export const Chat: FC<Props> = ({ roomId, room }) => {
     setMessages((prev) => [...prev, newMessage]);
   };
 
+  const handleMessage = (event: { target: { value: string } }) => {
+    const inputValue = event.target.value;
+
+    validateForm(inputValue);
+
+    if (!messageError && inputValue.length <= 150) {
```
Comment (silimarius) [inline src/components/chat/chat.tsx:52]: Define 150 as a global constant or check if we already have one

File: src/components/input-field/input-field.tsx [hunk 6]
```diff
@@ -1,28 +1,36 @@
...
+import { type FC } from "react";
 import { text } from "~/assets/text/index.js";
+import { SendButton } from "~/components/send-button/index.js";
 import { styles } from "./styles.js";
 
-type Props = Pick<ButtonProps, "onClick"> & Omit<TextFieldProps, "onClick">;
+type Props = Pick<ButtonProps, "onClick"> &
+  Omit<TextFieldProps, "onClick"> & {
+    validationError?: string;
+  };
```
Comment (silimarius) [inline src/components/input-field/input-field.tsx:15]: I would still keep the text field onClick and declare your own onSubmit. It is clearer when you use the component

Comment (silimarius) [reply src/components/input-field/input-field.tsx:15]:
```ts
interface Props extends TextFieldProps {
  validationError?: string;
  onSubmit: MouseEventHandler<HTMLButtonElement>
}
```

File: src/components/input-field/text-input-field.tsx [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+          fullWidth
+          {...rest}
+        />
+        <PrimaryButton
+          onClick={onClick}
+          aria-label={"send-button"}
+          disabled={!!validationError}
+          sx={{ "&:disabled": { border: "none" } }}
+        >
+          Confirm
```
Comment (silimarius) [inline src/components/input-field/text-input-field.tsx:87]: move to text file

**Review by silimarius — CHANGES_REQUESTED** [review]

File: src/components/chat/chat.tsx (hunk 3 above)
Comment (carlos-kryha) [reply src/components/chat/chat.tsx]: I feel like changes like this are unnecessary, hard to argue one is clearer than the other

File: src/components/input-field/input-field.tsx (hunk 6 above)
Comment (carlos-kryha) [reply src/components/input-field/input-field.tsx:15]: if you choose to go the `onSubmit` route, it would need to be defined within a `<form>` tag in the parent component, and you would need to add `type="submit"` to the button within TextField (no need to pass an onSubmit prop) somthing like this

```
const TextFieldButton = () =>
  <>
    <InputField onChange={onChangeProp}/>
    <Button type="submit" />
  </>

const Parent = () => 
  <form onSubmit={handleSubmit}>
    <TextFieldButton onChange={...} />
  </form>
```

**Review by carlos-kryha — APPROVED** [review]

File: src/components/input-field/input-field.tsx (hunk 6 above)
Comment (silimarius) [reply src/components/input-field/input-field.tsx]: `onClick` makes me think of clicking the input field if i am using the component. no matter the implementation that lays behind, what i am doing is submitting the data, thus it makes sense to call the event `onSubmit`. then that `onSubmit` can also be passed to the button's `onClick`, no need for a form. the important thing is that on a higher level I know clearly which action I am performing

File: src/components/chat/chat.tsx (hunk 5 above)
Comment (silimarius) [reply src/components/chat/chat.tsx]: Tbh now I don't even see the point in separating `validateForm` from this function. It's way more clear if the parsing is done here and in the `else` clause we also set the error state

File: src/constants/validation.ts [hunk 8]
```diff
@@ -28,6 +29,11 @@ export const validation = {
       min: 1,
       error: invalidTextLength(1, 320),
     },
+    chatMessage: {
+      max: MAX_CHARACTERS_CHAT_MESSAGE,
+      min: 1,
+      error: "max 150 characters",
```
Comment (ramidecodes) [inline src/constants/validation.ts:35]: Replace the hardcoded value with the actual constant value.

**Review by ramidecodes — CHANGES_REQUESTED** [review]

**Review by silimarius — APPROVED** [review]

**Review by ramidecodes — APPROVED** [review]
