### PR TITLE
fix(select username): update design and refactor validation

### LINKED ISSUE #246: Update "Username Select" page with latest design
https://www.figma.com/file/gyPGZoLbpWROi2CJIqbYvO/Botbusters-Design?type=design&node-id=651-19704&mode=design&t=eZ81dgsC2tjWdKSE-4

### PR DESCRIPTION
**Pull request by carlos-kryha**
closes #246 

### Description

Implementation of the username select page. Includes:
- [x] refactor validation of usernames to be shared across api and frontend
- [x] style page according to designs

### CODE REVIEW

File: src/assets/text/general.ts [hunk 1]
```diff
@@ -28,6 +28,12 @@ export const general = {
   clickChat: "Click on the chat to open messages",
   username: "AnonymousBuster",
   newCredits: "new",
+  enterUsername: "enter username",
+  usernameRules: "Max 12 Characters, no spaces.",
```
Comment (ramidecodes) [inline src/assets/text/general.ts:32]: add "no special characters"

**Review by ramidecodes — APPROVED** [review]

File: src/components/tables/components/row-create-username/row-create-username.tsx [hunk 2]
```diff
@@ -1,69 +1,63 @@
...
 }) => {
   const [username, setUsername] = useState("");
+  const [error, setError] = useState("");
 
   useEffect(() => {
     const name = getRandomUsername();
     setUsername(name.replace(/[0-9]/g, ""));
   }, []);
 
+  const validateUsername = (name: string) => {
```
Comment (ramidecodes) [inline src/components/tables/components/row-create-username/row-create-username.tsx:27]: Apparently you can do something like this to simplify the logic:
```TS 
const usernameSchema = z.string().min(validation.username.min, validation.username.error.tooShort)
                             .max(validation.username.max, validation.username.error.tooLong)
                             .regex(/^[a-zA-Z0-9_\-.]*$/, validation.username.error.specialCharacters);

const validateUsername = (name) => {
  let error = "";

  // Combine regex, min, max checks into one
  const result = usernameSchema.safeParse(name);
  if (!result.success) {
    error = result.error.issues[0].message; // Get the first validation error message
  } else if (profanityFilter.exists(name)) {
    error = validation.username.error.profanity;
  } else if (name.includes(" ")) {
    error = validation.username.error.space;
  }

  setError(error); // Assuming setError is defined elsewhere to handle setting the error message
};
```

**Review by ramidecodes — APPROVED** [review]

File: src/components/tables/components/row-create-username/row-create-username.tsx (hunk 2 above)
Comment (carlos-kryha) [reply src/components/tables/components/row-create-username/row-create-username.tsx:27]: oh, sweet I'll use that
