### PR TITLE
Fix(frontend structure): tidy up page components and layout

### LINKED ISSUE #164: Tidy up frontend structure: page-component-container
### Description
Inconsistencies in the use of the page-component-container structure make the frontend codebase difficult to understand and maintain

### Examples
[`src/pages/index.tsx`](https://github.com/Kryha/bot-busters/blob/main/src/pages/index.tsx) renders a container instead of a page
[`src/containers/user-stats/user-stats.tsx`](https://github.com/Kryha/bot-busters/blob/main/src/components/user-stats/user-stats.tsx) renders `<UserMenu />` which contains the header within it, this should be the other way around (`<header><user menu/><header>`)

### Proposed Solution
To avoid big changes and keep things moving I suggest focusing on the layout and page components and making sure those follow a consistent and intuitive structure. The changes should be purely structural and not affect logic. This would help with #163, #162 and a few other planned tasks

### PR DESCRIPTION
**Pull request by carlos-kryha**
### Problem
Fixes #164. The current `src/pages` directory is mostly used to route "page" components defined in `src/containers`. The `containers` name is unintuitive and using `src/pages` in this way adds unnecessary complexity. Additionally, the navigation bar implementation is all over the place and can be simplified significantly

### Solution
Since content in `src/pages` is automatically served by nextjs, create a single file per page under `src/pages` which can serve as the entry point for each route. Page components are then responsible for any route-related state, as well as rendering components/containers that make up the ui

One limitation of next's [Pages Router](https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts) approach is the inability to have style files "bundled" within a directory (like the rest of the codebase does), to get around this, styles will be moved to a new directory: `src/styles/pages/<page-name>`

example structure for leaderboard page:
```
> src/

  > pages/
    - leaderboard.tsx (route entry point, imports styles and components to render page, may contain route logic and state)

  > styles/
    - leaderboard.ts (styles exclusive to leaderboard page)

  > components/
    > tables/
      - leaderboard-table.tsx (component to be used within pages/other components)
```

The navigation bar was refactored to remove unused/unnecessary code and limit its state to a single component instead of 3 separate ones, it is also the only visual component within the app's layout

### CODE REVIEW

File: src/components/main-menu/navbar-menu.tsx [hunk 1]
```diff
@@ -14,15 +15,15 @@ import {
...
+  setSoundOn: (value: boolean) => void;
 }
 
-export const Header: FC<Props> = ({ handleClose }) => {
+export const NavbarMenu: FC<Props> = ({ handleClose, soundOn, setSoundOn }) => {
   const router = useRouter();
-  // TODO: Implement sound hook
-  const [sound, setSound] = useState(true);
 
   const onSoundClick = () => {
```
Comment (ramidecodes) [inline src/components/main-menu/navbar-menu.tsx:25]: Should we call this toggleSound, or you want to have the same naming as the hook in the component?

File: src/components/navbar/navbar.tsx [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+  setOpen,
+  disconnect,
+  points,
+}) => {
+  const router = useRouter();
+  const [soundOn, setSoundOn] = useState(true);
+  const isVerifiedUserAndPlayed = isVerifiedUser && isGamePlayed;
+  const title = isVerifiedUserAndPlayed ? username : text.general.dailyScore;
+
+  const logout = async () => {
```
Comment (ramidecodes) [inline src/components/navbar/navbar.tsx:42]: Since it's referring to the action of logging out and not just a static logout component this should be called "logOut" (action). (I know this is very nitty picking hehe)

File: src/components/navbar/styles.ts [hunk 3]
```diff
@@ -1,7 +1,23 @@
...
+
 import { breakpoints, theme } from "~/styles/theme.js";
 
 export const styles = {
+  container: {
+    position: "absolute",
+    top: 0,
+    left: 0,
+    right: 0,
+    zIndex: 2,
```
Comment (ramidecodes) [inline src/components/navbar/styles.ts:11]: Is it worth adding some values for zIndex as constants in the design system declarations?

File: src/pages/leaderboard.tsx [hunk 4]
```diff
@@ -1,16 +1,15 @@
...
 import { useSession } from "next-auth/react";
 import { Box, Typography } from "@mui/material";
-
 import { type LeaderboardData } from "~/types/index.js";
 import { isValidSession } from "~/utils/session.js";
 import { AddScoreTable, LeaderboardTable } from "~/components/tables/index.js";
 import { leaderboardData } from "~/constants/index.js";
 import { text } from "~/assets/text/index.js";
-import { styles } from "./styles.js";
+import { styles } from "../styles/pages/leaderboard.js";
```
Comment (ramidecodes) [inline src/pages/leaderboard.tsx:9]: Should we use "~" for referencing the path?

File: src/pages/player-profile.tsx [hunk 5]
```diff
@@ -10,9 +10,9 @@ import { fakeUsername } from "~/constants/fake-data/landing.js";
 import { isValidSession } from "~/utils/session.js";
 import { PlayerTable } from "~/components/index.js";
 import { fakePlayerProfile } from "~/constants/fake-data/player-profile.jsx";
-import { styles } from "./styles.js";
+import { styles } from "../styles/pages/player-profile.js";
```
Comment (ramidecodes) [inline src/pages/player-profile.tsx:13]: Same: "~"

File: src/pages/username-select.tsx [hunk 6]
```diff
@@ -1,30 +1,15 @@
...
-    width: "100%",
-    alignItems: "center",
-  },
-  container: {
-    position: "relative",
-    overflow: "hidden",
-    height: "100vh",
-  } satisfies SxProps,
-};
+import { styles } from '../styles/pages/username-select';
```
Comment (ramidecodes) [inline src/pages/username-select.tsx:12]: "~"

**Review by ramidecodes — CHANGES_REQUESTED** [review]
Looks good...
Just so minor changes...

File: src/components/navbar/navbar.tsx [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+import { MainMenu } from "../main-menu/index.js";
+import { pages } from "~/router.js";
+
+interface Props {
+  isVerifiedUser: boolean;
+  isGamePlayed: boolean;
+  username: string;
+  open: boolean;
+  setOpen: (open: boolean) => void;
+  disconnect: () => Promise<void>;
```
Comment (silimarius) [inline src/components/navbar/navbar.tsx:24]:
```suggestion
  disconnectWallet: () => Promise<void>;
```

File: src/components/navbar/navbar.tsx [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+    sessionStorage.clear();
+  };
+  
+  const onSoundClick = () => {
+    setSoundOn(!soundOn);
+  };
+
+  const handleNavigation = (path: string) => {
+    void router.push(path);
+  };
```
Comment (silimarius) [inline src/components/navbar/navbar.tsx:54]: redundant function, does not add anything

File: src/components/navbar/navbar.tsx [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+  const isVerifiedUserAndPlayed = isVerifiedUser && isGamePlayed;
+  const title = isVerifiedUserAndPlayed ? username : text.general.dailyScore;
+
+  const logout = async () => {
+    await signOut();
+    await disconnect();
+    sessionStorage.clear();
+  };
+  
+  const onSoundClick = () => {
```
Comment (silimarius) [inline src/components/navbar/navbar.tsx:48]:
```suggestion
  const toggleSound = () => {
```
`on` prefix should be used in Props to indicate an event, not when defining functions

File: src/components/navbar/navbar.tsx [hunk 10]
```diff
@@ -0,0 +1,90 @@
...
+import { useRouter } from "next/router";
+
+import { text } from "~/assets/text/index.js";
+import { styles } from "./styles.js";
+import {
+  BotBustersIcon,
+  SoundOffIcon,
+  SoundOnIcon,
+  UserIcon,
+} from "~/assets/icons";
```
Comment (silimarius) [inline src/components/navbar/navbar.tsx:13]:
```suggestion
} from "~/assets/icons/index.js";
```
at least I believe so lol

File: src/containers/layout/layout.tsx [hunk 11]
```diff
@@ -6,29 +6,28 @@ import { isVerifiedSession } from "~/utils/session.js";
...
-import { UserStats } from "~/components/user-stats/index.js";
-
+import { Navbar } from "~/components/navbar/index.js";
 import { styles } from "./styles.js";
 
 export const Layout: FC<StackProps> = ({ children }) => {
   const { data: sessionData } = useSession();
   const isVerifiedUser = isVerifiedSession(sessionData);
-  const [open, setOpen] = useState(false);
+  const [menuIsOpen, setMenuIsOpen] = useState(false);
```
Comment (silimarius) [inline src/containers/layout/layout.tsx:15]:
```suggestion
  const [navbarIsOpen, setNavbarIsOpen] = useState(false);
```
since you renamed the component

File: src/pages/index.tsx [hunk 12]
```diff
@@ -1,5 +1,65 @@
...
+          text={text.homepage.openDaily}
+        />
+        <PixelButton onClick={openAboutHandler} text={text.homepage.about} />
+      </Stack>
+      <TopRanked players={TOP_RANKED_PLAYERS} />
+    </Stack>
+  );
+};
+
+export default Homepage;
```
Comment (silimarius) [inline src/pages/index.tsx:65]: run prettier

File: src/pages/index.tsx [hunk 13]
```diff
@@ -1,5 +1,65 @@
...
+import { useRouter } from "next/router.js";
+import { text } from "~/assets/text/index.js";
+import { TopRanked } from "~/components/index.js";
+import { api } from "~/utils/api.js";
+import { pages } from "~/router.js";
+import { TOP_RANKED_PLAYERS } from "~/constants/index.js";
+import { isValidSession } from "~/utils/session.js";
+import { styles } from "../styles/pages/homepage.js";
+import { BotBustersLogo } from "~/assets/icons/index.js";
+import { PixelButton } from "~/components/pixel-button/index.js";
```
Comment (silimarius) [inline src/pages/index.tsx:12]: Order imports like this
```
<lib imports>
<blank line>
<imports from root (~/)>
<blank line>
<relative imports>
```

File: src/pages/leaderboard.tsx [hunk 14]
```diff
@@ -74,3 +73,5 @@ export const LeaderBoard = () => {
     </>
   );
 };
+
+export default LeaderBoard;
```
Comment (silimarius) [inline src/pages/leaderboard.tsx:77]: run prettier

File: src/pages/player-profile.tsx [hunk 15]
```diff
@@ -52,3 +52,5 @@ export const UserProfile = () => {
     </Stack>
   );
 };
+
+export default PlayerProfile;
```
Comment (silimarius) [inline src/pages/player-profile.tsx:56]: prettier

File: src/pages/rules.tsx [hunk 16]
```diff
@@ -11,4 +11,4 @@ function Rules() {
   );
 }
 
-export default Rules;
+export default Rules;
```
Comment (silimarius) [inline src/pages/rules.tsx:14]: prettier

File: src/pages/support.tsx [hunk 17]
```diff
@@ -11,4 +11,4 @@ function Support() {
   );
 }
 
-export default Support;
+export default Support;
```
Comment (silimarius) [inline src/pages/support.tsx:14]: prettier

**Review by silimarius — APPROVED** [review]

File: src/components/navbar/navbar.tsx (hunk 2 above)
Comment (carlos-kryha) [reply src/components/navbar/navbar.tsx]: can do, though personally when I read logout I always read action

File: src/pages/leaderboard.tsx (hunk 4 above)
Comment (carlos-kryha) [reply src/pages/leaderboard.tsx]: good one, they should be good now. wondering if I can configure the automatic imports feature on vscode to use absolute paths

File: src/components/navbar/styles.ts (hunk 3 above)
Comment (carlos-kryha) [reply src/components/navbar/styles.ts:11]: In my opinion z-index is the devil and the ideal frontend need not use it. That being said yeah that's probably a good idea. I'm not familiar with the design system implementation here but I'm happy to take a deeper look, shall I add a todo?

File: src/components/navbar/navbar.tsx (hunk 8 above)
Comment (carlos-kryha) [reply src/components/navbar/navbar.tsx:49]: I disagree, the alternative would be moving the logic to the jsx which makes it harder to find/easier to miss
```tsx
    <Stack sx={styles.container}>
      <Stack sx={styles.wrapper}>
        <Stack sx={styles.userName}>
          <UserIcon />
          <Typography variant="h3">{text.general.username}</Typography>
        </Stack>
        <Button
          variant="text"
          sx={styles.mainLogo}
          onClick={() => void router.push(pages.home)}
        >
```
defining onClick handle fns above the jsx helps with that

File: src/components/navbar/navbar.tsx (hunk 9 above)
Comment (carlos-kryha) [reply src/components/navbar/navbar.tsx:43]: this is an `onClick` handler, which is an event

File: src/containers/layout/layout.tsx (hunk 11 above)
Comment (carlos-kryha) [reply src/containers/layout/layout.tsx:15]: this actually tracks the main menu, the navbar is always visible so it doesn't have a "closed" state

File: src/components/navbar/styles.ts (hunk 3 above)
Comment (carlos-kryha) [reply src/components/navbar/styles.ts:11]: added todo

File: src/components/navbar/navbar.tsx (hunk 7 above)
Comment (carlos-kryha) [reply src/components/navbar/navbar.tsx]: implemented the change, watch out when using the suggest feature, if I were to commit that without adjusting other files it would break the app

**Review by ramidecodes — APPROVED** [review]

File: src/components/main-menu/navbar-menu.tsx (hunk 1 above)
Comment (carlos-kryha) [reply src/components/main-menu/navbar-menu.tsx:25]: if you are referring to the `setSound` prop, "toggle" wouldn't apply since the fn takes a boolean as input
