### PR TITLE
bug(voting): not allowed to vote and earn points when no message is send by player

### LINKED ISSUE #264: Add notification on voting stage when player is not allowed to vote
If player didn't send any message during the chat phase, they are not allow to vote.
* [x] Disable Confirm button if player hasn't send any message in during the chat session
* [x] Add notice reading: "Voting is only available for players participating in the chat."
* [x] Prevent assignment of Achievements

### PR DESCRIPTION
**Pull request by Mautjee**
## Description

The player now sees a message stating why they are not allowed to vote and earn point this round.
 
## Related Issues

closes #264 

## Changes Made

- [BE] Added check if the user has send a message
- [FE] Changed styles and text for message when user is not able to vote

### CODE REVIEW

File: src/server/service/match.ts [hunk 1]
```diff
@@ -276,6 +276,10 @@ export class Match {
         (p) => p.userId !== player.userId,
       );
 
+      // Checking if the player did send a message this match
+      if (!this._messages.some((message) => message.sender === player.userId))
+        return { ...player };
```
Comment (silimarius) [inline src/server/service/match.ts:281]: You can just check if player voted. this is redundant and out of the scope of this method

**Review by silimarius — CHANGES_REQUESTED** [review]

**Review by silimarius — APPROVED** [review]
