### PR TITLE
fix(how-to-play page): implement how to play page

### LINKED ISSUE #198: Implement "How to play" Page
https://www.figma.com/file/gyPGZoLbpWROi2CJIqbYvO/Botbusters-Design?type=design&node-id=1205-212&mode=design&t=eZ81dgsC2tjWdKSE-4

https://docs.google.com/document/d/10QuDrdWG3A7jlDfYpFLaM4nLlMMFvI78TA3-6MN9mjQ/edit#heading=h.oms7ldjpjar0

### PR DESCRIPTION
**Pull request by carlos-kryha**
Fixes #198 

### Description
Implement how to play page based on the following [desings](https://www.figma.com/file/gyPGZoLbpWROi2CJIqbYvO/Botbusters-Design?type=design&node-id=1205%3A212&mode=design&t=szVj5A4OpjJvC1Ud-1)

1. Add two UI components:
- BulletPoint (because the font is missing the bullet symbol)
- NumberedSection (number and title on top of content)

2. Add three page section components: 
- GameRules
- PointsAndPenalties
- PlayerProfile

3. Refactor HowtoPlay page using the components above

### Result
Screenshot 2024-01-18 at 11 21 04

### CODE REVIEW

File: src/components/game-rules/game-rules.tsx [hunk 1]
```diff
@@ -0,0 +1,54 @@
+import React, { type FC } from "react";
+import { Typography } from "@mui/material";
+
+import { text as copywrite } from "~/assets/text";
+import { BulletPoint, type BulletPointProps } from "~/components";
+import { NumberedSection } from "~/components/numbered-text-section/index.js";
+import { styles } from "~/styles/pages/how-to-play.js";
+import { theme } from "~/styles/theme";
```
Comment (privilegemendes) [inline src/components/game-rules/game-rules.tsx:8]: `import { theme } from "~/styles/theme.js";`

File: src/assets/text/how-to-play.ts [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+  ],
+  numberedSection: {
+    matchmaking: [
+      "Players enter a lobby.",
+      "The lobby randomly mixes humans and bots, with a minimum of one other human and at least one bot per match.",
+      "Waiting time varies to prevent players from guessing the mix of humans and bots.",
+      "Players are randomly assigned one of five characters for easy identification in the chatroom.",
+    ],
+    chatting: [
+      "Five players interact and chat to determine who’s a bot.",
```
Comment (privilegemendes) [inline src/assets/text/how-to-play.ts:21]: change the apostrophe " ' ". Figma bullshit

File: src/components/numbered-text-section/styles.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
+import { theme } from "~/styles/theme.js";
+import type { SxStyleRecord } from "~/types/sx-style-record";
```
Comment (privilegemendes) [inline src/components/numbered-text-section/styles.ts:2]: `import type { SxStyleRecord } from "~/types/sx-style-record.js";`

File: src/components/player-profiles/player-profiles.tsx [hunk 4]
```diff
@@ -0,0 +1,39 @@
+import React, { type FC } from "react";
+import { Typography } from "@mui/material";
+
+import { text } from "~/assets/text";
+import { BulletPoint } from "~/components";
+import { theme } from "~/styles/theme";
```
Comment (privilegemendes) [inline src/components/player-profiles/player-profiles.tsx:6]: import { text } from "~/assets/text/index.js";
import { BulletPoint } from "~/components/index.js";
import { theme } from "~/styles/theme.js";

File: src/components/points-and-penalties/points-and-penalties.tsx [hunk 5]
```diff
@@ -0,0 +1,46 @@
+import React, { type FC } from "react";
+import { Typography } from "@mui/material";
+
+import { text } from "~/assets/text";
+import { BulletPoint } from "~/components";
+import { theme } from "~/styles/theme";
```
Comment (privilegemendes) [inline src/components/points-and-penalties/points-and-penalties.tsx:6]: `import { text } from "~/assets/text/index.js";
import { BulletPoint } from "~/components/index.js";
import { theme } from "~/styles/theme.js";`

File: src/pages/how-to-play.tsx [hunk 6]
```diff
@@ -0,0 +1,55 @@
+import { Stack, Typography } from "@mui/material";
+import React, { type FC } from "react";
+import { text as copywrite } from "~/assets/text";
```
Comment (privilegemendes) [inline src/pages/how-to-play.tsx:3]: `import { text as copywrite } from "~/assets/text/index.js";`

File: src/assets/text/how-to-play.ts [hunk 7]
```diff
@@ -0,0 +1,86 @@
+// TODO: add missing links
+export const howToPlay = {
+  headings: {
```
Comment (ramidecodes) [inline src/assets/text/how-to-play.ts:3]: What about having this in lower case and adding a style to show them in all caps?

File: src/styles/globals.css [hunk 8]
```diff
@@ -6,8 +6,7 @@
 }
 
 a {
-  color: #5CFF00;
-  /* text-decoration: none; */
+  color: #7cff33;
```
Comment (privilegemendes) [inline src/styles/globals.css:9]: hmm, let's keep the links color: #5CFF00 since the text in the how to play page are color: #7cff33

File: src/components/points-and-penalties/index.ts [hunk 9]
```diff
@@ -0,0 +1 @@
+export * from "./points-and-penalties";
```
Comment (privilegemendes) [inline src/components/points-and-penalties/index.ts:1]: `export * from "./points-and-penalties.jsx";`

File: src/components/player-profiles/index.ts [hunk 10]
```diff
@@ -0,0 +1 @@
+export * from "./player-profiles";
```
Comment (privilegemendes) [inline src/components/player-profiles/index.ts:1]: export * from "./player-profiles.jsx";

File: src/components/game-rules/index.ts [hunk 11]
```diff
@@ -0,0 +1 @@
+export * from "./game-rules";
```
Comment (privilegemendes) [inline src/components/game-rules/index.ts:1]: export * from "./game-rules.jsx";

File: src/components/game-rules/game-rules.tsx [hunk 12]
```diff
@@ -0,0 +1,54 @@
+import React, { type FC } from "react";
+import { Typography } from "@mui/material";
+
+import { text as copywrite } from "~/assets/text";
```
Comment (ramidecodes) [inline src/components/game-rules/game-rules.tsx:4]: Remember to add the file extension.
We definitely need an extra linting rule for this.

**Comment by privilegemendes** [comment]
src/components/main-menu/menu-options.tsx
```
      <MenuOptionsButton onClick={() => handleNavigation(pages.howToPlay)}>
        {text.general.howToPlay}
      </MenuOptionsButton>
```

**Review by ramidecodes — APPROVED** [review]

**Review by Mautjee — APPROVED** [review]
