### PR TITLE
bug(authentication) fix double clicking to proceed

### LINKED ISSUE #194: After clicking "add to leaderboard" trigger user login or user creation flow
Currently user needs to click twice after connecting wallet after a game log in.

### PR DESCRIPTION
**Pull request by Mautjee**
## Description 

User now presses once to proceed to the next stage

## Changes

closes #194

### CODE REVIEW

File: src/containers/results/results.tsx [hunk 1]
```diff
@@ -48,8 +47,10 @@ export const Results: FC<Props> = ({ gainedScore, botsBusted, totalBots }) => {
             signature,
             callbackUrl: pages.home,
           });
+          setMergeRequested(false);
         } else {
           await router.push(pages.usernameSelect);
+          setMergeRequested(false);
```
Comment (silimarius) [inline src/containers/results/results.tsx:53]: this should be above router.push, else this gets triggered after components unmounts and that's a leak

**Review by silimarius — CHANGES_REQUESTED** [review]

File: src/containers/results/results.tsx (hunk 1 above)
Comment (silimarius) [reply src/containers/results/results.tsx:53]: This would not solve my comment since it would still be executed after

**Review by ramidecodes — APPROVED** [review]

File: src/containers/results/results.tsx (hunk 1 above)
Comment (silimarius) [reply src/containers/results/results.tsx:53]: Then we're back to the beginning and the double clicking would be back

**Review by silimarius — APPROVED** [review]
