### PR TITLE
fix(page-layout): implement layout component for more consisten styles across pages 

### LINKED ISSUE #260: Update Static page layout styles
Page components are lacking a shared layout, which leads to inconsistencies in UI when navigating between them. Implement a layout component to enable page components to share as much css as possible

### PR DESCRIPTION
**Pull request by carlos-kryha**
closes #260 

### Description
All page components are now exported using PageLayout set to a relative width of `67vw` and constrained to `max 1440px min 1015px`, ensuring the layout is consistent on wider viewports. It also (optionally) renders the page header.

### Changes:
- [x] implement `<PageLayout />` component with an optional `title` prop
- [x] refactor page components to use `<PageLayout />`
- [x] move css from page components to layout when possible
- [x] refactor how-to-play page styles to use a single 
- [x] improve `numbered-section` and `bullet-point`

https://github.com/Kryha/bot-busters/assets/97608823/45928809-5d53-489c-8bcb-368d411fe93a

### CODE REVIEW

File: src/components/authentication/username-select.tsx [hunk 1]
```diff
@@ -5,12 +5,11 @@ import { useRouter } from "next/router.js";
 import { api } from "~/utils/api.js";
 import { RowCreateUsername } from "~/components/tables/components/index.js";
 import { pages } from "~/router.js";
+import { text } from "~/assets/text/index.js";
+import { PageLayout } from "~/containers/page-layout/page-layout.jsx";
```
Comment (silimarius) [inline src/components/authentication/username-select.tsx:9]:
```suggestion
import { PageLayout } from "~/containers/page-layout/index.js";
```

File: src/components/numbered-text-section/numbered-text-section.tsx [hunk 2]
```diff
@@ -21,7 +21,7 @@ export const NumberedSection: FC<Props> = ({ number, title, content }) => {
         <Typography variant="body1" sx={styles.title}>
           {title}
         </Typography>
-        {content}
+        <>{content}</>
```
Comment (silimarius) [inline src/components/numbered-text-section/numbered-text-section.tsx:24]: delete useless tags

File: src/containers/page-layout/page-layout.tsx [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+  title,
+  children,
+}) => (
+  <Stack sx={styles.container}>
+    <Stack sx={styles.content}>
+      {title && <PageHeader text={title} />}
+      {children}
+    </Stack>
+  </Stack>
+);
```
Comment (silimarius) [inline src/containers/page-layout/page-layout.tsx:30]:
```suggestion
export const PageLayout: FC<{ title?: string } & StackProps> = ({
  title,
  children,
  stackProps,
}) => (
  <Stack sx={styles.container} {...stackProps}>
    <Stack sx={styles.content}>
      {title && <PageHeader text={title} />}
      {children}
    </Stack>
  </Stack>
);
```
since you are declaring it in the type let's be consistent

File: src/pages/404.tsx [hunk 4]
```diff
@@ -1,23 +1,13 @@
...
-  container: {
-    height: "100vh",
-    alignItems: "center",
-    justifyContent: "center",
-  },
-};
+const Custom404: FC = () => (
+  <Stack mt="20vh">
+    <PageLayout title={text.general.pageNotFound} />
+  </Stack>
```
Comment (silimarius) [inline src/pages/404.tsx:10]: Isn't this an anti-pattern now? PageLayout is supposed to be the parent element in pages

File: src/pages/about.tsx [hunk 5]
```diff
@@ -1,23 +1,24 @@
 import { Stack, Typography } from "@mui/material";
 
 import { text } from "~/assets/text/index.js";
-import { PageHeader } from "~/containers/page-header/index.js";
+import { PageLayout } from "~/containers/page-layout";
```
Comment (silimarius) [inline src/pages/about.tsx:4]: import from index.js

File: src/pages/login.tsx [hunk 6]
```diff
@@ -12,6 +11,7 @@ import {
   type LoginStage,
   SignIn,
 } from "~/components/index.js";
+import { PageLayout } from "~/containers/page-layout/page-layout.jsx";
```
Comment (silimarius) [inline src/pages/login.tsx:14]: import from index

File: src/pages/player-profile.tsx [hunk 7]
```diff
@@ -20,16 +20,14 @@ const PlayerProfile = () => {
 
   if (user.isLoading) {
     return (
-      <Stack sx={styles.mainContainer}>
+      <Stack width="100%" pt="40vh" alignItems="center">
         <CircularProgress />
       </Stack>
```
Comment (silimarius) [inline src/pages/player-profile.tsx:25]: Can we make it a LoadingPage component so we re-use the same for other pages as well?

File: src/server/service/leaderboard/leaderboard.ts [hunk 8]
```diff
@@ -114,8 +114,6 @@ const storeOnChain = async () => {
       slices.map((slice) => executeUpdateScores(slice)),
     ).then((txs) => txs.filter((tx) => !tx.isSuccess));
   } while (tryCount > 0 && failedTransactions.length);
-
-  console.log("Executed transactions");
```
Comment (silimarius) [inline src/server/service/leaderboard/leaderboard.ts:118]: Please leave it here. This is a useful log

**Review by silimarius — CHANGES_REQUESTED** [review]

File: src/components/numbered-text-section/numbered-text-section.tsx (hunk 2 above)
Comment (carlos-kryha) [reply src/components/numbered-text-section/numbered-text-section.tsx:24]: That tag is actually needed. In this case content is of type `ReactNode` which accepts an array of components (for example in `game-rules.tsx` content is an array of `<Bullet-point />`).

Since content is in a flex div with title, not grouping content into a component would cause alignment issues

File: src/containers/page-layout/page-layout.tsx (hunk 3 above)
Comment (carlos-kryha) [reply src/containers/page-layout/page-layout.tsx:30]: This is intentional, I'm adding the `StackProps` type because I want to use the `children` prop but I do not want the layout taking any other prop from its parent. This will ensure every instance of <PageLayout /> serves the same styles to its children

File: src/components/numbered-text-section/numbered-text-section.tsx (hunk 2 above)
Comment (silimarius) [reply src/components/numbered-text-section/numbered-text-section.tsx:24]: Makes sense, although now I wonder why it was working before lol

File: src/pages/404.tsx (hunk 4 above)
Comment (carlos-kryha) [reply src/pages/404.tsx:10]: Since a few routes don't actually use this layout (splash, game, match-making, etc), this gives us the flexibility to use the layout on the pages that are compatible, and maintain the `src/pages` directory as entry point. 

The other option would be to use the layout feature of Next but have some logic to skip it on certain routes, let me know if you think that would be better and I can see about refactoring

File: src/containers/page-layout/page-layout.tsx (hunk 3 above)
Comment (silimarius) [reply src/containers/page-layout/page-layout.tsx:30]: Then just declare children as ReactNode and don't extend the type since those other props will never be used and that may lead to misusing this component in the future

File: src/server/service/leaderboard/leaderboard.ts (hunk 8 above)
Comment (silimarius) [reply src/server/service/leaderboard/leaderboard.ts:118]: Actually make it a `console.info` please

File: src/pages/player-profile.tsx (hunk 7 above)
Comment (carlos-kryha) [reply src/pages/player-profile.tsx:25]: yeah, we might as well, adding

File: src/components/numbered-text-section/numbered-text-section.tsx (hunk 2 above)
Comment (carlos-kryha) [reply src/components/numbered-text-section/numbered-text-section.tsx:24]: to be clear `ReactNode` can also be a single component, in which case that tag is indeed useless 😅

**Review by silimarius — APPROVED** [review]
