### PR TITLE
fix(authentication): display username of logged in user

### LINKED ISSUE #168: Show Username in the header when user is logged in
* [ ] If user is logged in show username
* [ ] If user is not logged show "AnonymousBuster"

### PR DESCRIPTION
**Pull request by Mautjee**
## Description

Now the username of the logged in user is shown in the top left corner of the menu bar
 
## Related Issues

Closes #168 

## Changes Made

- [FE] Change logic to show username

### CODE REVIEW

File: src/containers/home/index.tsx [hunk 1]
```diff
@@ -29,6 +34,11 @@ export const Homepage = () => {
       console.error(error);
     }
   };
+  useEffect(() => {
+    if (isUnverifiedSession(sessionData) && !isVerifiedSession(sessionData)) {
```
Comment (ramidecodes) [inline src/containers/home/index.tsx:38]: Same issue as the previous PR. 
Add a TODO, to clarify this predicates

**Review by ramidecodes — APPROVED** [review]

**Review by ramidecodes — APPROVED** [review]
