### PR TITLE
fix(results): proof of humanity tooltip hover

### LINKED ISSUE #325: Update styles for Poof of humanity tooltips in Results View
[Designs](https://www.figma.com/file/gyPGZoLbpWROi2CJIqbYvO/Botbusters-Design?type=design&node-id=1969-34365&mode=design&t=HkdefwVAxY3DKbq1-4)
* [x] Title of the tooltip should be same color as character color
* [x] Tooltip should have the same size and location as shown in the designs 3/4 of the width of the container
* [x] Tooltip should only be shown on hovering the character portrait
* [x] Only show tooltip for human players
    * [x] Add "<CharName> was played by an unverified human". In case is Anon player

### PR DESCRIPTION
**Pull request by Mautjee**
## Description

This pr changes the behaviour of the proof of humanity tooltip. Now it behaves as a tooltip and shows on hover
 
## Related Issues

closes #325 

## Changes Made

- [FE] Added hover state to player component

### CODE REVIEW

File: src/components/players/player-proofs/player-proofs.tsx [hunk 1]
```diff
@@ -15,13 +15,26 @@ interface Props {
...
   const character = CHARACTERS[playerProof.characterId];
   const textColor = `${character.color}.main`;
 
+  if (!playerProof.isVerified && !playerProof.isBot)
+    return (
+      <Stack sx={styles.container}>
+        <Stack sx={styles.resultsHeading}>
+          <Typography variant="body1" color={textColor}>
+            <Box component="span">{character.name} </Box>
+            {"was played by an unverified human!"}
```
Comment (ramidecodes) [inline src/components/players/player-proofs/player-proofs.tsx:33]: Move this to a the text assets

File: src/components/players/player/player.tsx [hunk 2]
```diff
@@ -28,13 +29,41 @@ export const Player: FC<Props> = ({
...
   const { name, color } = character;
   const textColor = `${color}.main`;
 
   const isBotSelected = stage === "voting" && isSelected;
 
+  const containerRef = useRef<HTMLDivElement | null>(null);
+
+  useEffect(() => {
+    const onMouseEnter = () => {
+      if (onHoverPlayer) {
```
Comment (ramidecodes) [inline src/components/players/player/player.tsx:44]: Why do you need to check `onHOverPlayer`? Can this be undefined?

**Review by ramidecodes — APPROVED** [review]

File: src/components/players/player-proofs/player-proofs.tsx [hunk 3]
```diff
@@ -15,13 +15,26 @@ interface Props {
...
+  const playerProof = otherPlayers.find(
+    (player) => player.characterId === proofCharacterId,
+  );
+
+  if (!playerProof) return <></>;
 
   const character = CHARACTERS[playerProof.characterId];
   const textColor = `${character.color}.main`;
 
+  if (!playerProof.isVerified && !playerProof.isBot)
```
Comment (silimarius) [inline src/components/players/player-proofs/player-proofs.tsx:27]: please add braces

File: src/components/players/player-proofs/player-proofs.tsx (hunk 1 above)
Comment (silimarius) [inline src/components/players/player-proofs/player-proofs.tsx:33]: put in text file

**Review by silimarius — APPROVED** [review]

File: src/components/players/player/player.tsx (hunk 2 above)
Comment (Mautjee) [reply src/components/players/player/player.tsx:44]: Yes it can be undefined... this `player` component is used by quite a few other components which do not use a on hover state.

**Review by ramidecodes — APPROVED** [review]
